/**
 * Claude Integration Handler
 * Manages Claude-specific operations including profile switching, rate limiting, and OAuth token detection
 */

import * as os from 'os';
import * as fs from 'fs';
import { promises as fsPromises } from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';
import { IPC_CHANNELS } from '../../shared/constants';
import { getClaudeProfileManager, initializeClaudeProfileManager } from '../claude-profile-manager';
import { getCredentialsFromKeychain, clearKeychainCache } from '../claude-profile/credential-utils';
import { getUsageMonitor } from '../claude-profile/usage-monitor';
import { getEmailFromConfigDir } from '../claude-profile/profile-utils';
import * as OutputParser from './output-parser';
import * as SessionHandler from './session-handler';
import * as PtyManager from './pty-manager';
import { debugLog, debugError } from '../../shared/utils/debug-logger';
import { escapeShellArg, escapeForWindowsDoubleQuote, buildCdCommand } from '../../shared/utils/shell-escape';
import { getClaudeCliInvocation, getClaudeCliInvocationAsync } from '../claude-cli-utils';
import { isWindows } from '../platform';
import type {
  TerminalProcess,
  WindowGetter,
  RateLimitEvent,
  OAuthTokenEvent,
  OnboardingCompleteEvent
} from './types';

// ============================================================================
// AUTH TERMINAL ID PATTERN CONSTANTS
// ============================================================================

/**
 * Regular expression pattern for matching auth terminal IDs.
 * Auth terminals follow the format: claude-login-{profileId}-{timestamp}
 *
 * Profile IDs are generated by generateProfileId() in profile-utils.ts:
 * - 'default' for the default profile
 * - Sanitized profile names: name.toLowerCase().replace(/[^a-z0-9]+/g, '-')
 *   Examples: "Work" -> "work", "My Profile" -> "my-profile"
 *
 * The pattern matches:
 * - 'claude-login-' prefix
 * - Profile ID: lowercase letters, numbers, and hyphens (non-greedy to stop at timestamp)
 * - '-' separator before timestamp
 * - Timestamp: 13+ digit Unix timestamp
 *
 * @see claude-code-handlers.ts where the ID format is generated
 * @see profile-utils.ts generateProfileId() for profile ID format
 */
const AUTH_TERMINAL_ID_PATTERN = /^claude-login-([a-z0-9-]+)-(\d{13,})$/;

/**
 * Extract profile ID from an auth terminal ID.
 *
 * @param terminalId - Terminal ID to parse (e.g., 'claude-login-work-1737298800000')
 * @returns The profile ID (e.g., 'work', 'my-profile', 'default'), or null if not an auth terminal
 *
 * @example
 * extractProfileIdFromAuthTerminalId('claude-login-default-1737298800000') // 'default'
 * extractProfileIdFromAuthTerminalId('claude-login-work-1737298800000') // 'work'
 * extractProfileIdFromAuthTerminalId('claude-login-my-profile-1737298800000') // 'my-profile'
 * extractProfileIdFromAuthTerminalId('regular-terminal-1') // null
 */
function extractProfileIdFromAuthTerminalId(terminalId: string): string | null {
  const match = terminalId.match(AUTH_TERMINAL_ID_PATTERN);
  return match ? match[1] : null;
}

/**
 * Mask email address for logging to prevent PII exposure.
 *
 * @param email - Email address to mask
 * @returns Masked email (e.g., 'user@example.com' -> 'u***@e***.com')
 *
 * @example
 * maskEmail('john.doe@example.com') // 'j***@e***.com'
 * maskEmail('a@b.co') // 'a***@b***.co'
 * maskEmail('') // ''
 */
function maskEmail(email: string | null | undefined): string {
  if (!email || typeof email !== 'string') {
    return '';
  }

  const atIndex = email.indexOf('@');
  if (atIndex === -1) {
    // Not a valid email format, mask most of it
    return email.charAt(0) + '***';
  }

  const localPart = email.substring(0, atIndex);
  const domainPart = email.substring(atIndex + 1);

  // Mask local part (keep first char)
  const maskedLocal = localPart.charAt(0) + '***';

  // Mask domain part (keep first char and TLD)
  const domainDotIndex = domainPart.indexOf('.');
  if (domainDotIndex === -1) {
    // No TLD, just mask after first char
    const maskedDomain = domainPart.charAt(0) + '***';
    return `${maskedLocal}@${maskedDomain}`;
  }

  const domainName = domainPart.substring(0, domainDotIndex);
  const tld = domainPart.substring(domainDotIndex); // includes the dot
  const maskedDomain = domainName.charAt(0) + '***' + tld;

  return `${maskedLocal}@${maskedDomain}`;
}

function normalizePathForBash(envPath: string): string {
  return isWindows() ? envPath.replace(/;/g, ':') : envPath;
}

/**
 * Generate temp file content for OAuth token based on platform
 *
 * On Windows, creates a .bat file with set command using double-quote syntax;
 * on Unix, creates a shell script with export.
 *
 * @param token - OAuth token value
 * @returns Content string for the temp file
 */
function generateTokenTempFileContent(token: string): string {
  if (isWindows()) {
    // Windows: Use double-quote syntax for set command to handle special characters
    // Format: set "VARNAME=value" - quotes allow spaces and special chars in value
    // For values inside double quotes, use escapeForWindowsDoubleQuote() because
    // caret is literal inside double quotes in cmd.exe (only " needs escaping).
    const escapedToken = escapeForWindowsDoubleQuote(token);
    return `@echo off\r\nset "CLAUDE_CODE_OAUTH_TOKEN=${escapedToken}"\r\n`;
  }
  // Unix/macOS: Use export with single-quoted value
  return `export CLAUDE_CODE_OAUTH_TOKEN=${escapeShellArg(token)}\n`;
}

/**
 * Get the file extension for temp files based on platform
 *
 * @returns File extension including the dot (e.g., '.bat' on Windows, '' on Unix)
 */
function getTempFileExtension(): string {
  return isWindows() ? '.bat' : '';
}

/**
 * Build PATH environment variable prefix for Claude CLI invocation.
 *
 * On Windows, uses semicolon separators and cmd.exe escaping.
 * On Unix/macOS, uses colon separators and bash escaping.
 *
 * @param pathEnv - PATH environment variable value
 * @returns Empty string if no PATH, otherwise platform-specific PATH prefix
 */
function buildPathPrefix(pathEnv: string): string {
  if (!pathEnv) {
    return '';
  }

  if (isWindows()) {
    // Windows: Use semicolon-separated PATH with double-quote escaping
    // Format: set "PATH=value" where value uses semicolons
    // For values inside double quotes, use escapeForWindowsDoubleQuote() because
    // caret is literal inside double quotes in cmd.exe (only " needs escaping).
    const escapedPath = escapeForWindowsDoubleQuote(pathEnv);
    return `set "PATH=${escapedPath}" && `;
  }

  // Unix/macOS: Use colon-separated PATH with bash escaping
  // Format: PATH='value' where value uses colons
  const normalizedPath = normalizePathForBash(pathEnv);
  return `PATH=${escapeShellArg(normalizedPath)} `;
}

/**
 * Escape a command for safe use in shell commands.
 *
 * On Windows, wraps in double quotes for cmd.exe. Since the value is inside
 * double quotes, we use escapeForWindowsDoubleQuote() (only escapes embedded
 * double quotes as ""). Caret escaping is NOT used inside double quotes.
 * On Unix/macOS, wraps in single quotes for bash.
 *
 * @param cmd - The command to escape
 * @returns The escaped command safe for use in shell commands
 */
function escapeShellCommand(cmd: string): string {
  if (isWindows()) {
    // Windows: Wrap in double quotes and escape only embedded double quotes
    // Inside double quotes, caret is literal, so use escapeForWindowsDoubleQuote()
    const escapedCmd = escapeForWindowsDoubleQuote(cmd);
    return `"${escapedCmd}"`;
  }
  // Unix/macOS: Wrap in single quotes for bash
  return escapeShellArg(cmd);
}

/**
 * Flag for YOLO mode (skip all permission prompts)
 * Extracted as constant to ensure consistency across invokeClaude and invokeClaudeAsync
 */
const YOLO_MODE_FLAG = ' --dangerously-skip-permissions';

// ============================================================================
// SHARED HELPERS - Used by both sync and async invokeClaude
// ============================================================================

/**
 * Configuration for building Claude shell commands using discriminated union.
 * This provides type safety by ensuring the correct options are provided for each method.
 *
 * Note: Paths are NOT escaped - buildClaudeShellCommand handles platform-specific escaping.
 */
type ClaudeCommandConfig =
  | { method: 'default' }
  | { method: 'temp-file'; tempFile: string }
  | { method: 'config-dir'; configDir: string };

/**
 * Build the shell command for invoking Claude CLI.
 *
 * Generates the appropriate command string based on the invocation method:
 * - 'default': Simple command execution
 * - 'temp-file': Sources OAuth token from temp file, then removes it
 * - 'config-dir': Sets CLAUDE_CONFIG_DIR for custom profile location
 *
 * All non-default methods include history-safe prefixes (HISTFILE=, HISTCONTROL=)
 * to prevent sensitive data from appearing in shell history (Unix/macOS only).
 *
 * On Windows, uses cmd.exe/PowerShell compatible syntax without bash-specific commands.
 * The temp file method on Windows uses a batch file approach with inline environment setup.
 *
 * @param cwdCommand - Command to change directory (empty string if no change needed)
 * @param pathPrefix - PATH prefix for Claude CLI (empty string if not needed)
 * @param escapedClaudeCmd - Shell-escaped Claude CLI command
 * @param config - Configuration object with method and required options (discriminated union)
 * @param extraFlags - Optional extra flags to append to the command (e.g., '--dangerously-skip-permissions')
 * @returns Complete shell command string ready for terminal.pty.write()
 *
 * @example
 * // Default method (Unix/macOS)
 * buildClaudeShellCommand('cd /path && ', 'PATH=/bin ', 'claude', { method: 'default' });
 * // Returns: 'cd /path && PATH=/bin claude\r'
 *
 * // Temp file method (Unix/macOS)
 * buildClaudeShellCommand('', '', 'claude', { method: 'temp-file', tempFile: '/tmp/token' });
 * // Returns: 'clear && HISTFILE= HISTCONTROL=ignorespace bash -c "source /tmp/token && rm -f /tmp/token && exec claude"\r'
 *
 * // Temp file method (Windows)
 * buildClaudeShellCommand('', '', 'claude.cmd', { method: 'temp-file', tempFile: 'C:\\Users\\...\\token.bat' });
 * // Returns: 'cls && call C:\\Users\\...\\token.bat && claude.cmd\r'
 */
export function buildClaudeShellCommand(
  cwdCommand: string,
  pathPrefix: string,
  escapedClaudeCmd: string,
  config: ClaudeCommandConfig,
  extraFlags?: string
): string {
  const fullCmd = extraFlags ? `${escapedClaudeCmd}${extraFlags}` : escapedClaudeCmd;
  const isWin = isWindows();

  switch (config.method) {
    case 'temp-file':
      if (isWin) {
        // Windows: Use batch file approach with 'call' command
        // The temp file on Windows is a .bat file that sets CLAUDE_CODE_OAUTH_TOKEN
        // We use 'cls' instead of 'clear', and 'call' to execute the batch file
        //
        // SECURITY: Environment variables set via 'call' persist in memory
        // after the batch file is deleted, so we can safely delete the file
        // immediately after sourcing it (before running Claude).
        //
        // For paths inside double quotes (call "..." and del "..."), use
        // escapeForWindowsDoubleQuote() instead of escapeShellArgWindows()
        // because caret is literal inside double quotes in cmd.exe.
        const escapedTempFile = escapeForWindowsDoubleQuote(config.tempFile);
        return `cls && ${cwdCommand}${pathPrefix}call "${escapedTempFile}" && del "${escapedTempFile}" && ${fullCmd}\r`;
      } else {
        // Unix/macOS: Use bash with source command and history-safe prefixes
        const escapedTempFile = escapeShellArg(config.tempFile);
        return `clear && ${cwdCommand}HISTFILE= HISTCONTROL=ignorespace ${pathPrefix}bash -c "source ${escapedTempFile} && rm -f ${escapedTempFile} && exec ${fullCmd}"\r`;
      }

    case 'config-dir':
      if (isWin) {
        // Windows: Set environment variable using double-quote syntax
        // For values inside double quotes (set "VAR=value"), use
        // escapeForWindowsDoubleQuote() because caret is literal inside
        // double quotes in cmd.exe (only double quotes need escaping).
        const escapedConfigDir = escapeForWindowsDoubleQuote(config.configDir);
        return `cls && ${cwdCommand}set "CLAUDE_CONFIG_DIR=${escapedConfigDir}" && ${pathPrefix}${fullCmd}\r`;
      } else {
        // Unix/macOS: Use bash with config dir and history-safe prefixes
        const escapedConfigDir = escapeShellArg(config.configDir);
        return `clear && ${cwdCommand}HISTFILE= HISTCONTROL=ignorespace CLAUDE_CONFIG_DIR=${escapedConfigDir} ${pathPrefix}bash -c "exec ${fullCmd}"\r`;
      }

    default:
      return `${cwdCommand}${pathPrefix}${fullCmd}\r`;
  }
}

/**
 * Profile information for terminal title generation
 */
interface ProfileInfo {
  /** Profile name for display */
  name?: string;
  /** Whether this is the default profile */
  isDefault?: boolean;
}

/**
 * Check if a terminal should be auto-renamed when Claude is invoked.
 * Returns false if:
 * - Terminal already has a Claude-related title (already renamed)
 * - Terminal has a user-customized name (not "Terminal X" pattern)
 *
 * This prevents aggressive renaming on every Claude invocation and
 * preserves user-customized terminal names.
 */
export function shouldAutoRenameTerminal(currentTitle: string): boolean {
  // Already has Claude title - don't rename again
  if (currentTitle === 'Claude' || currentTitle.startsWith('Claude (')) {
    return false;
  }

  // Check if it's a default terminal name (Terminal 1, Terminal 2, etc.)
  // Only these can be auto-renamed on first Claude invocation
  const defaultNamePattern = /^Terminal \d+$/;
  return defaultNamePattern.test(currentTitle);
}

/**
 * Callback type for session capture
 */
type SessionCaptureCallback = (terminalId: string, projectPath: string, startTime: number) => void;

/**
 * Finalize terminal state after invoking Claude.
 *
 * Updates terminal title, sends IPC notification to renderer, persists session,
 * and calls the session capture callback. This consolidates the post-invocation
 * logic used by both sync and async invoke methods.
 *
 * @param terminal - The terminal process to update
 * @param activeProfile - The profile being used (or undefined for default)
 * @param projectPath - The project path (for session capture)
 * @param startTime - Timestamp when invocation started
 * @param getWindow - Function to get the BrowserWindow
 * @param onSessionCapture - Callback for session capture
 *
 * @example
 * finalizeClaudeInvoke(
 *   terminal,
 *   { name: 'Work', isDefault: false },
 *   '/path/to/project',
 *   Date.now(),
 *   () => mainWindow,
 *   (id, path, time) => console.log('Session captured')
 * );
 */
export function finalizeClaudeInvoke(
  terminal: TerminalProcess,
  activeProfile: ProfileInfo | undefined,
  projectPath: string | undefined,
  startTime: number,
  getWindow: WindowGetter,
  onSessionCapture: SessionCaptureCallback
): void {
  // Only auto-rename if terminal has default name (first Claude invocation)
  // This preserves user-customized names and prevents renaming on every invocation
  if (shouldAutoRenameTerminal(terminal.title)) {
    const title = activeProfile && !activeProfile.isDefault
      ? `Claude (${activeProfile.name})`
      : 'Claude';
    terminal.title = title;

    // Notify renderer of title change
    const win = getWindow();
    if (win) {
      win.webContents.send(IPC_CHANNELS.TERMINAL_TITLE_CHANGE, terminal.id, title);
    }
  }

  // Persist session if project path is available
  if (terminal.projectPath) {
    SessionHandler.persistSession(terminal);
  }

  // Call session capture callback if project path provided
  if (projectPath) {
    onSessionCapture(terminal.id, projectPath, startTime);
  }
}

/**
 * Handle rate limit detection and profile switching
 */
export function handleRateLimit(
  terminal: TerminalProcess,
  data: string,
  lastNotifiedRateLimitReset: Map<string, string>,
  getWindow: WindowGetter,
  switchProfileCallback: (terminalId: string, profileId: string) => Promise<void>
): void {
  const resetTime = OutputParser.extractRateLimitReset(data);
  if (!resetTime) {
    return;
  }

  const lastNotifiedReset = lastNotifiedRateLimitReset.get(terminal.id);
  if (resetTime === lastNotifiedReset) {
    return;
  }

  lastNotifiedRateLimitReset.set(terminal.id, resetTime);
  console.warn('[ClaudeIntegration] Rate limit detected, reset:', resetTime);

  const profileManager = getClaudeProfileManager();
  const currentProfileId = terminal.claudeProfileId || 'default';

  try {
    const rateLimitEvent = profileManager.recordRateLimitEvent(currentProfileId, resetTime);
    console.warn('[ClaudeIntegration] Recorded rate limit event:', rateLimitEvent.type);
  } catch (err) {
    console.error('[ClaudeIntegration] Failed to record rate limit event:', err);
  }

  const autoSwitchSettings = profileManager.getAutoSwitchSettings();
  const bestProfile = profileManager.getBestAvailableProfile(currentProfileId);

  const win = getWindow();
  if (win) {
    win.webContents.send(IPC_CHANNELS.TERMINAL_RATE_LIMIT, {
      terminalId: terminal.id,
      resetTime,
      detectedAt: new Date().toISOString(),
      profileId: currentProfileId,
      suggestedProfileId: bestProfile?.id,
      suggestedProfileName: bestProfile?.name,
      autoSwitchEnabled: autoSwitchSettings.autoSwitchOnRateLimit
    } as RateLimitEvent);
  }

  if (autoSwitchSettings.enabled && autoSwitchSettings.autoSwitchOnRateLimit && bestProfile) {
    console.warn('[ClaudeIntegration] Auto-switching to profile:', bestProfile.name);
    switchProfileCallback(terminal.id, bestProfile.id).then(_result => {
      console.warn('[ClaudeIntegration] Auto-switch completed');
    }).catch(err => {
      console.error('[ClaudeIntegration] Auto-switch failed:', err);
    });
  }
}

/**
 * Handle OAuth token detection and auto-save
 * Also handles "Login successful" detection for claude /login flow
 */
export function handleOAuthToken(
  terminal: TerminalProcess,
  data: string,
  getWindow: WindowGetter
): void {
  // Extract profile ID from auth terminal ID pattern (if this is an auth terminal)
  const profileId = extractProfileIdFromAuthTerminalId(terminal.id);

  // First check for "Login successful" message (claude /login flow)
  // This is the primary detection method since tokens aren't displayed in output
  if (OutputParser.hasLoginSuccess(data) && profileId) {
    console.warn('[ClaudeIntegration] Login success detected for profile:', profileId);

    const emailFromOutput = OutputParser.extractEmail(terminal.outputBuffer);
    const profileManager = getClaudeProfileManager();
    const profile = profileManager.getProfile(profileId);

    if (!profile) {
      console.error('[ClaudeIntegration] Profile not found for login success:', profileId);
      return;
    }

    // Clear Keychain cache to get fresh credentials
    clearKeychainCache(profile.configDir);

    // Extract token from Keychain using the profile's configDir
    const keychainCreds = getCredentialsFromKeychain(profile.configDir, true);

    // Check if there was a keychain access error (not just "not found")
    if (keychainCreds.error) {
      console.error('[ClaudeIntegration] Keychain access error:', keychainCreds.error);
      // Don't retry on keychain failures - they won't resolve with retries
      return;
    }

    if (keychainCreds.token) {
      // NOTE: We intentionally do NOT store the OAuth token in the profile.
      // Storing causes AutoClaude to use a stale cached token instead of letting
      // Claude CLI read fresh tokens from Keychain (which auto-refreshes).
      // See: docs/LONG_LIVED_AUTH_PLAN.md for full context.

      // Get email from multiple sources, preferring config file as the authoritative source
      // Terminal output parsing can be corrupted by ANSI escape codes
      let email = emailFromOutput || keychainCreds.email;

      // Fallback/validation: Read from Claude's config file (authoritative source)
      const configEmail = getEmailFromConfigDir(profile.configDir);
      if (configEmail) {
        if (!email) {
          console.warn('[ClaudeIntegration] Email not found in output/keychain, using config file:', maskEmail(configEmail));
          email = configEmail;
        } else if (configEmail !== email) {
          // Config file email is different (terminal extraction might be corrupt)
          console.warn('[ClaudeIntegration] Email from output differs from config file, using config file:', {
            outputEmail: maskEmail(email),
            configEmail: maskEmail(configEmail)
          });
          email = configEmail;
        }
      }

      if (email) {
        profile.email = email;
      }
      profile.isAuthenticated = true;
      profileManager.saveProfile(profile);

      console.warn('[ClaudeIntegration] Profile credentials verified via Keychain (not caching token):', profileId);

      // Set flag to watch for Claude's ready state (onboarding complete)
      terminal.awaitingOnboardingComplete = true;

      const win = getWindow();
      if (win) {
        // needsOnboarding: true tells the UI to show "complete setup" message
        // instead of "success" - user should finish Claude's onboarding before closing
        win.webContents.send(IPC_CHANNELS.TERMINAL_OAUTH_TOKEN, {
          terminalId: terminal.id,
          profileId,
          email: emailFromOutput || keychainCreds.email || profile?.email,
          success: true,
          needsOnboarding: true,
          detectedAt: new Date().toISOString()
        } as OAuthTokenEvent);
      }
    } else {
      // Token not in Keychain yet, but profile may still be authenticated via configDir
      // Check if profile has valid auth (credentials exist in configDir)
      const hasCredentials = profileManager.hasValidAuth(profileId);

      if (hasCredentials) {
        console.warn('[ClaudeIntegration] Profile credentials verified (no Keychain token):', profileId);

        // Set flag to watch for Claude's ready state (onboarding complete)
        terminal.awaitingOnboardingComplete = true;

        const win = getWindow();
        if (win) {
          // needsOnboarding: true tells the UI to show "complete setup" message
          // instead of "success" - user should finish Claude's onboarding before closing
          win.webContents.send(IPC_CHANNELS.TERMINAL_OAUTH_TOKEN, {
            terminalId: terminal.id,
            profileId,
            email: emailFromOutput || profile?.email,
            success: true,
            needsOnboarding: true,
            detectedAt: new Date().toISOString()
          } as OAuthTokenEvent);
        }
      } else {
        console.warn('[ClaudeIntegration] Login successful but Keychain token not found and no credentials in configDir - user may need to complete authentication manually');
      }
    }
    return;
  }

  // Fallback: Check for raw OAuth token in output (legacy method)
  const token = OutputParser.extractOAuthToken(data);
  if (!token) {
    return;
  }

  console.warn('[ClaudeIntegration] OAuth token detected in output');

  let email = OutputParser.extractEmail(terminal.outputBuffer);

  if (profileId) {
    // Update profile metadata (but NOT the token - see docs/LONG_LIVED_AUTH_PLAN.md)
    const profileManager = getClaudeProfileManager();
    const profile = profileManager.getProfile(profileId);

    if (profile) {
      // Fallback/validation: Read email from Claude's config file (authoritative source)
      const configEmail = getEmailFromConfigDir(profile.configDir);
      if (configEmail) {
        if (!email) {
          console.warn('[ClaudeIntegration] Email not found in output, using config file:', maskEmail(configEmail));
          email = configEmail;
        } else if (configEmail !== email) {
          console.warn('[ClaudeIntegration] Email from output differs from config file, using config file:', {
            outputEmail: maskEmail(email),
            configEmail: maskEmail(configEmail)
          });
          email = configEmail;
        }
      }

      if (email) {
        profile.email = email;
      }
      profile.isAuthenticated = true;
      profileManager.saveProfile(profile);

      // Clear keychain cache so next getCredentialsFromKeychain() fetches fresh token
      clearKeychainCache(profile.configDir);
      console.warn('[ClaudeIntegration] Profile credentials verified (not caching token):', profileId);

      const win = getWindow();
      if (win) {
        win.webContents.send(IPC_CHANNELS.TERMINAL_OAUTH_TOKEN, {
          terminalId: terminal.id,
          profileId,
          email,
          success: true,
          detectedAt: new Date().toISOString()
        } as OAuthTokenEvent);
      }
    } else {
      console.error('[ClaudeIntegration] Profile not found for OAuth token:', profileId);
    }
  } else {
    // No profile-specific terminal, update active profile metadata (GitHub OAuth flow, etc.)
    // NOTE: We do NOT store the token - see docs/LONG_LIVED_AUTH_PLAN.md
    console.warn('[ClaudeIntegration] OAuth token detected in non-profile terminal, updating active profile metadata');
    const profileManager = getClaudeProfileManager();
    const activeProfile = profileManager.getActiveProfile();

    // Defensive null check for active profile
    if (!activeProfile) {
      console.error('[ClaudeIntegration] Failed to update profile: no active profile found');
      const win = getWindow();
      if (win) {
        win.webContents.send(IPC_CHANNELS.TERMINAL_OAUTH_TOKEN, {
          terminalId: terminal.id,
          profileId: undefined,
          email,
          success: false,
          message: 'No active profile found',
          detectedAt: new Date().toISOString()
        } as OAuthTokenEvent);
      }
      return;
    }

    // Fallback/validation: Read email from Claude's config file (authoritative source)
    const configEmail = getEmailFromConfigDir(activeProfile.configDir);
    if (configEmail) {
      if (!email) {
        console.warn('[ClaudeIntegration] Email not found in output, using config file:', maskEmail(configEmail));
        email = configEmail;
      } else if (configEmail !== email) {
        console.warn('[ClaudeIntegration] Email from output differs from config file, using config file:', {
          outputEmail: maskEmail(email),
          configEmail: maskEmail(configEmail)
        });
        email = configEmail;
      }
    }

    if (email) {
      activeProfile.email = email;
    }
    activeProfile.isAuthenticated = true;
    profileManager.saveProfile(activeProfile);

    // Clear keychain cache so next getCredentialsFromKeychain() fetches fresh token
    clearKeychainCache(activeProfile.configDir);
    console.warn('[ClaudeIntegration] Active profile credentials verified (not caching token):', activeProfile.name);

    const win = getWindow();
    if (win) {
      win.webContents.send(IPC_CHANNELS.TERMINAL_OAUTH_TOKEN, {
        terminalId: terminal.id,
        profileId: activeProfile.id,
        email,
        success: true,
        detectedAt: new Date().toISOString()
      } as OAuthTokenEvent);
    }
  }
}

/**
 * Handle onboarding complete detection
 * Called when terminal output indicates Claude Code is ready after login/onboarding
 *
 * This detects the Claude Code welcome screen that appears after successful login,
 * which includes patterns like "Welcome back", "Claude Code v2.x", or subscription
 * tier info like "Claude Max". When detected, it notifies the frontend to auto-close
 * the auth terminal.
 */
export function handleOnboardingComplete(
  terminal: TerminalProcess,
  data: string,
  getWindow: WindowGetter
): void {
  // Only check if we're waiting for onboarding to complete
  if (!terminal.awaitingOnboardingComplete) {
    return;
  }

  // Check if output shows Claude Code welcome screen (onboarding complete indicators)
  if (!OutputParser.isOnboardingCompleteOutput(data)) {
    return;
  }

  console.warn('[ClaudeIntegration] Onboarding complete detected for terminal:', terminal.id);

  // Clear the flag
  terminal.awaitingOnboardingComplete = false;

  // Extract profile ID from terminal ID pattern (claude-login-{profileId}-*)
  const profileId = extractProfileIdFromAuthTerminalId(terminal.id) || undefined;

  // Try to extract email from the welcome screen (e.g., "user@example.com's Organization")
  // Note: extractEmail automatically strips ANSI escape codes internally
  let email = OutputParser.extractEmail(data);
  if (!email) {
    email = OutputParser.extractEmail(terminal.outputBuffer);
  }

  // Fallback: If terminal extraction failed or might be corrupt, read directly from Claude's config file
  // This is the authoritative source and doesn't suffer from ANSI escape code issues
  const profileManager = getClaudeProfileManager();
  const profile = profileId ? profileManager.getProfile(profileId) : null;

  if (!email && profile?.configDir) {
    const configEmail = getEmailFromConfigDir(profile.configDir);
    if (configEmail) {
      console.warn('[ClaudeIntegration] Email not found in terminal output, using config file:', maskEmail(configEmail));
      email = configEmail;
    }
  }

  // Validate email looks correct (basic sanity check)
  // If terminal extraction gave us a truncated email but config file has the correct one, prefer config
  if (email && profile?.configDir) {
    const configEmail = getEmailFromConfigDir(profile.configDir);
    if (configEmail && configEmail !== email) {
      // Config file email is different - it's more authoritative
      console.warn('[ClaudeIntegration] Terminal email differs from config file, using config file:', {
        terminalEmail: maskEmail(email),
        configEmail: maskEmail(configEmail)
      });
      email = configEmail;
    }
  }

  console.warn('[ClaudeIntegration] Email extraction attempt:', {
    profileId,
    foundEmail: maskEmail(email),
    dataLength: data.length,
    bufferLength: terminal.outputBuffer.length
  });

  // Update profile with email if found and profile exists
  // Always update - the newly extracted email from re-authentication should overwrite any stale/truncated email
  if (profileId && email && profile) {
    const previousEmail = profile.email;
    profile.email = email;
    profileManager.saveProfile(profile);
    if (previousEmail !== email) {
      console.warn('[ClaudeIntegration] Updated profile email from welcome screen:', profileId, maskEmail(email), '(was:', maskEmail(previousEmail), ')');
    }
  }

  const win = getWindow();
  if (win) {
    win.webContents.send(IPC_CHANNELS.TERMINAL_ONBOARDING_COMPLETE, {
      terminalId: terminal.id,
      profileId,
      detectedAt: new Date().toISOString()
    } as OnboardingCompleteEvent);
  }

  // Trigger immediate usage fetch after successful re-authentication
  // This gives the user immediate feedback that their account is working
  if (profileId) {
    try {
      const usageMonitor = getUsageMonitor();
      if (usageMonitor) {
        // Clear any auth failure status for this profile since they just re-authenticated
        usageMonitor.clearAuthFailedProfile(profileId);

        console.warn('[ClaudeIntegration] Triggering immediate usage fetch after re-authentication:', profileId);

        // Switch to this profile if it's not already active, then fetch usage
        const profileManager = getClaudeProfileManager();

        // Also clear the migration flag if this profile was migrated to an isolated directory
        // This prevents the auth failure modal from showing again on next startup
        if (profileManager.isProfileMigrated(profileId)) {
          profileManager.clearMigratedProfile(profileId);
          console.warn('[ClaudeIntegration] Cleared migration flag for re-authenticated profile:', profileId);
        }
        const activeProfile = profileManager.getActiveProfile();
        if (activeProfile?.id !== profileId) {
          profileManager.setActiveProfile(profileId);
        }

        // Small delay to allow profile switch to settle, then trigger usage fetch
        setTimeout(() => {
          usageMonitor.checkNow();
        }, 500);
      }
    } catch (error) {
      console.error('[ClaudeIntegration] Failed to trigger post-auth usage fetch:', error);
    }
  }
}

/**
 * Handle Claude session ID capture
 */
export function handleClaudeSessionId(
  terminal: TerminalProcess,
  sessionId: string,
  getWindow: WindowGetter
): void {
  terminal.claudeSessionId = sessionId;
  console.warn('[ClaudeIntegration] Captured Claude session ID:', sessionId);

  if (terminal.projectPath) {
    SessionHandler.updateClaudeSessionId(terminal.projectPath, terminal.id, sessionId);
  }

  const win = getWindow();
  if (win) {
    win.webContents.send(IPC_CHANNELS.TERMINAL_CLAUDE_SESSION, terminal.id, sessionId);
  }
}

/**
 * Handle Claude exit detection (user closed Claude, returned to shell)
 *
 * This is called when we detect that Claude has exited and the terminal
 * has returned to a shell prompt. This resets the Claude mode state
 * and notifies the renderer to update the UI.
 */
export function handleClaudeExit(
  terminal: TerminalProcess,
  getWindow: WindowGetter
): void {
  // Only handle if we're actually in Claude mode
  if (!terminal.isClaudeMode) {
    return;
  }

  console.warn('[ClaudeIntegration] Claude exit detected, resetting mode for terminal:', terminal.id);

  // Reset Claude mode state
  terminal.isClaudeMode = false;
  terminal.claudeSessionId = undefined;

  // Persist the session state change
  if (terminal.projectPath) {
    SessionHandler.persistSession(terminal);
  }

  // Notify renderer to update UI
  const win = getWindow();
  if (win) {
    win.webContents.send(IPC_CHANNELS.TERMINAL_CLAUDE_EXIT, terminal.id);
  }
}

/**
 * Shared command execution logic for profile-based invocation
 * Returns true if command was executed via configDir or temp-file method
 */
interface ExecuteProfileCommandOptions {
  needsEnvOverride: boolean;
  activeProfile: any;
  cwdCommand: string;
  pathPrefix: string;
  escapedClaudeCmd: string;
  extraFlags: string | undefined;
  terminal: TerminalProcess;
  profileManager: any;
  projectPath: string | undefined;
  startTime: number;
  getWindow: WindowGetter;
  onSessionCapture: SessionCaptureCallback;
  logPrefix: string;
}

function executeProfileCommand(options: ExecuteProfileCommandOptions): boolean {
  const {
    needsEnvOverride,
    activeProfile,
    cwdCommand,
    pathPrefix,
    escapedClaudeCmd,
    extraFlags,
    terminal,
    profileManager,
    projectPath,
    startTime,
    getWindow,
    onSessionCapture,
    logPrefix,
  } = options;

  if (!needsEnvOverride || !activeProfile || activeProfile.isDefault) {
    return false; // Use default method
  }

  // Prefer configDir over token because CLAUDE_CONFIG_DIR lets Claude Code
  // read full Keychain credentials including subscriptionType ("max") and rateLimitTier.
  // Using CLAUDE_CODE_OAUTH_TOKEN alone lacks tier info, causing "Claude API" display.
  if (activeProfile.configDir) {
    const command = buildClaudeShellCommand(
      cwdCommand,
      pathPrefix,
      escapedClaudeCmd,
      { method: 'config-dir', configDir: activeProfile.configDir },
      extraFlags
    );
    debugLog(`${logPrefix} Executing command (configDir method, history-safe)`);
    PtyManager.writeToPty(terminal, command);
    profileManager.markProfileUsed(activeProfile.id);
    finalizeClaudeInvoke(terminal, activeProfile, projectPath, startTime, getWindow, onSessionCapture);
    debugLog(`${logPrefix} ========== INVOKE CLAUDE COMPLETE (configDir) ==========`);
    return true;
  }

  // Legacy fallback: use temp-file method if only token is available
  const token = profileManager.getProfileToken(activeProfile.id);
  debugLog(`${logPrefix} Token retrieval:`, {
    hasToken: !!token
  });

  if (token) {
    const nonce = crypto.randomBytes(8).toString('hex');
    const tempFile = path.join(
      os.tmpdir(),
      `.claude-token-${Date.now()}-${nonce}${getTempFileExtension()}`
    );
    debugLog(`${logPrefix} Writing token to temp file:`, tempFile);
    fs.writeFileSync(tempFile, generateTokenTempFileContent(token), { mode: 0o600 });

    const command = buildClaudeShellCommand(
      cwdCommand,
      pathPrefix,
      escapedClaudeCmd,
      { method: 'temp-file', tempFile },
      extraFlags
    );
    debugLog(`${logPrefix} Executing command (temp file method, history-safe)`);
    PtyManager.writeToPty(terminal, command);
    profileManager.markProfileUsed(activeProfile.id);
    finalizeClaudeInvoke(terminal, activeProfile, projectPath, startTime, getWindow, onSessionCapture);
    debugLog(`${logPrefix} ========== INVOKE CLAUDE COMPLETE (temp file) ==========`);
    return true;
  }

  debugLog(`${logPrefix} WARNING: No token or configDir available for non-default profile`);
  return false;
}

/**
 * Async version of executeProfileCommand for non-blocking file operations
 * Returns true if command was executed via configDir or temp-file method
 */
async function executeProfileCommandAsync(options: ExecuteProfileCommandOptions): Promise<boolean> {
  const {
    needsEnvOverride,
    activeProfile,
    cwdCommand,
    pathPrefix,
    escapedClaudeCmd,
    extraFlags,
    terminal,
    profileManager,
    projectPath,
    startTime,
    getWindow,
    onSessionCapture,
    logPrefix,
  } = options;

  if (!needsEnvOverride || !activeProfile || activeProfile.isDefault) {
    return false; // Use default method
  }

  // Prefer configDir over token because CLAUDE_CONFIG_DIR lets Claude Code
  // read full Keychain credentials including subscriptionType ("max") and rateLimitTier.
  // Using CLAUDE_CODE_OAUTH_TOKEN alone lacks tier info, causing "Claude API" display.
  if (activeProfile.configDir) {
    const command = buildClaudeShellCommand(
      cwdCommand,
      pathPrefix,
      escapedClaudeCmd,
      { method: 'config-dir', configDir: activeProfile.configDir },
      extraFlags
    );
    debugLog(`${logPrefix} Executing command (configDir method, history-safe)`);
    PtyManager.writeToPty(terminal, command);
    profileManager.markProfileUsed(activeProfile.id);
    finalizeClaudeInvoke(terminal, activeProfile, projectPath, startTime, getWindow, onSessionCapture);
    debugLog(`${logPrefix} ========== INVOKE CLAUDE COMPLETE (configDir) ==========`);
    return true;
  }

  // Legacy fallback: use temp-file method if only token is available
  const token = profileManager.getProfileToken(activeProfile.id);
  debugLog(`${logPrefix} Token retrieval:`, {
    hasToken: !!token
  });

  if (token) {
    const nonce = crypto.randomBytes(8).toString('hex');
    const tempFile = path.join(
      os.tmpdir(),
      `.claude-token-${Date.now()}-${nonce}${getTempFileExtension()}`
    );
    debugLog(`${logPrefix} Writing token to temp file:`, tempFile);
    await fsPromises.writeFile(tempFile, generateTokenTempFileContent(token), { mode: 0o600 });

    const command = buildClaudeShellCommand(
      cwdCommand,
      pathPrefix,
      escapedClaudeCmd,
      { method: 'temp-file', tempFile },
      extraFlags
    );
    debugLog(`${logPrefix} Executing command (temp file method, history-safe)`);
    PtyManager.writeToPty(terminal, command);
    profileManager.markProfileUsed(activeProfile.id);
    finalizeClaudeInvoke(terminal, activeProfile, projectPath, startTime, getWindow, onSessionCapture);
    debugLog(`${logPrefix} ========== INVOKE CLAUDE COMPLETE (temp file) ==========`);
    return true;
  }

  debugLog(`${logPrefix} WARNING: No token or configDir available for non-default profile`);
  return false;
}

/**
 * Invoke Claude with optional profile override
 */
export function invokeClaude(
  terminal: TerminalProcess,
  cwd: string | undefined,
  profileId: string | undefined,
  getWindow: WindowGetter,
  onSessionCapture: (terminalId: string, projectPath: string, startTime: number) => void,
  dangerouslySkipPermissions?: boolean
): void {
  debugLog('[ClaudeIntegration:invokeClaude] ========== INVOKE CLAUDE START ==========');
  debugLog('[ClaudeIntegration:invokeClaude] Terminal ID:', terminal.id);
  debugLog('[ClaudeIntegration:invokeClaude] Requested profile ID:', profileId);
  debugLog('[ClaudeIntegration:invokeClaude] CWD:', cwd);
  debugLog('[ClaudeIntegration:invokeClaude] Dangerously skip permissions:', dangerouslySkipPermissions);

  // Compute extra flags for YOLO mode
  const extraFlags = dangerouslySkipPermissions ? YOLO_MODE_FLAG : undefined;

  // Track terminal state for cleanup on error
  const wasClaudeMode = terminal.isClaudeMode;
  const previousProfileId = terminal.claudeProfileId;

  try {
    terminal.isClaudeMode = true;
    // Store YOLO mode setting so it persists across profile switches
    terminal.dangerouslySkipPermissions = dangerouslySkipPermissions;
    SessionHandler.releaseSessionId(terminal.id);
    terminal.claudeSessionId = undefined;

    const startTime = Date.now();
    const projectPath = cwd || terminal.projectPath || terminal.cwd;

    const profileManager = getClaudeProfileManager();
    const activeProfile = profileId
      ? profileManager.getProfile(profileId)
      : profileManager.getActiveProfile();

    terminal.claudeProfileId = activeProfile?.id;

    debugLog('[ClaudeIntegration:invokeClaude] Profile resolution:', {
      previousProfileId,
      newProfileId: activeProfile?.id,
      profileName: activeProfile?.name,
      hasOAuthToken: !!activeProfile?.oauthToken,
      isDefault: activeProfile?.isDefault
    });

    const cwdCommand = buildCdCommand(cwd, terminal.shellType);
    const { command: claudeCmd, env: claudeEnv } = getClaudeCliInvocation();
    const escapedClaudeCmd = escapeShellCommand(claudeCmd);
    const pathPrefix = buildPathPrefix(claudeEnv.PATH || '');
    const needsEnvOverride: boolean = !!(profileId && profileId !== previousProfileId);

    debugLog('[ClaudeIntegration:invokeClaude] Environment override check:', {
      profileIdProvided: !!profileId,
      previousProfileId,
      needsEnvOverride
    });

    // Try to execute using profile-specific method (configDir or temp-file)
    const executed = executeProfileCommand({
      needsEnvOverride,
      activeProfile,
      cwdCommand,
      pathPrefix,
      escapedClaudeCmd,
      extraFlags,
      terminal,
      profileManager,
      projectPath,
      startTime,
      getWindow,
      onSessionCapture,
      logPrefix: '[ClaudeIntegration:invokeClaude]',
    });

    if (executed) {
      return; // Command already executed via configDir or temp-file method
    }

    // Fall back to default method
    if (activeProfile && !activeProfile.isDefault) {
      debugLog('[ClaudeIntegration:invokeClaude] Using terminal environment for non-default profile:', activeProfile.name);
    }

    const command = buildClaudeShellCommand(cwdCommand, pathPrefix, escapedClaudeCmd, { method: 'default' }, extraFlags);
    debugLog('[ClaudeIntegration:invokeClaude] Executing command (default method):', command);
    PtyManager.writeToPty(terminal, command);

    if (activeProfile) {
      profileManager.markProfileUsed(activeProfile.id);
    }

    finalizeClaudeInvoke(terminal, activeProfile, projectPath, startTime, getWindow, onSessionCapture);
    debugLog('[ClaudeIntegration:invokeClaude] ========== INVOKE CLAUDE COMPLETE (default) ==========');
  } catch (error) {
    // Reset terminal state on error to prevent inconsistent state
    terminal.isClaudeMode = wasClaudeMode;
    terminal.claudeSessionId = undefined;
    terminal.claudeProfileId = previousProfileId;
    debugError('[ClaudeIntegration:invokeClaude] Invocation failed:', error);
    debugError('[ClaudeIntegration:invokeClaude] Error details:', {
      terminalId: terminal.id,
      profileId,
      cwd,
      errorName: error instanceof Error ? error.name : 'Unknown',
      errorMessage: error instanceof Error ? error.message : String(error)
    });
    throw error; // Re-throw to allow caller to handle
  }
}

/**
 * Resume Claude session in the current directory
 *
 * Uses `claude --continue` which resumes the most recent conversation in the
 * current directory. This is simpler and more reliable than tracking session IDs,
 * since AI员工 already restores terminals to their correct cwd/projectPath.
 *
 * Note: The sessionId parameter is kept for backwards compatibility but is ignored.
 * Claude Code's --resume flag expects user-named sessions (set via /rename), not
 * internal session file IDs.
 */
export function resumeClaude(
  terminal: TerminalProcess,
  _sessionId: string | undefined,
  getWindow: WindowGetter
): void {
  // Track terminal state for cleanup on error
  const wasClaudeMode = terminal.isClaudeMode;

  try {
    terminal.isClaudeMode = true;
    SessionHandler.releaseSessionId(terminal.id);

    const { command: claudeCmd, env: claudeEnv } = getClaudeCliInvocation();
    const escapedClaudeCmd = escapeShellCommand(claudeCmd);
    const pathPrefix = buildPathPrefix(claudeEnv.PATH || '');

    // Always use --continue which resumes the most recent session in the current directory.
    // This is more reliable than --resume with session IDs since AI员工 already restores
    // terminals to their correct cwd/projectPath.
    //
    // Note: We clear claudeSessionId because --continue doesn't track specific sessions,
    // and we don't want stale IDs persisting through SessionHandler.persistSession().
    terminal.claudeSessionId = undefined;

    // Deprecation warning for callers still passing sessionId
    if (_sessionId) {
      console.warn('[ClaudeIntegration:resumeClaude] sessionId parameter is deprecated and ignored; using claude --continue instead');
    }

    const command = `${pathPrefix}${escapedClaudeCmd} --continue`;

    // Use PtyManager.writeToPty for safer write with error handling
    PtyManager.writeToPty(terminal, `${command}\r`);

    // Only auto-rename if terminal has default name
    // This preserves user-customized names and prevents renaming on every resume
    if (shouldAutoRenameTerminal(terminal.title)) {
      terminal.title = 'Claude';
      const win = getWindow();
      if (win) {
        win.webContents.send(IPC_CHANNELS.TERMINAL_TITLE_CHANGE, terminal.id, 'Claude');
      }
    }

    // Persist session
    if (terminal.projectPath) {
      SessionHandler.persistSession(terminal);
    }
  } catch (error) {
    // Reset terminal state on error to prevent inconsistent state
    terminal.isClaudeMode = wasClaudeMode;
    // Note: Don't restore claudeSessionId since --continue doesn't use session IDs
    debugError('[ClaudeIntegration:resumeClaude] Resume failed:', error);
    throw error; // Re-throw to allow caller to handle
  }
}

// ============================================================================
// ASYNC VERSIONS - Non-blocking alternatives for Electron main process
// ============================================================================

/**
 * Invoke Claude asynchronously (non-blocking)
 *
 * Safe to call from Electron main process without blocking the event loop.
 * Uses async CLI detection which doesn't block on subprocess calls.
 * Includes error handling and timeout protection to prevent hangs.
 */
export async function invokeClaudeAsync(
  terminal: TerminalProcess,
  cwd: string | undefined,
  profileId: string | undefined,
  getWindow: WindowGetter,
  onSessionCapture: (terminalId: string, projectPath: string, startTime: number) => void,
  dangerouslySkipPermissions?: boolean
): Promise<void> {
  // Track terminal state for cleanup on error
  const wasClaudeMode = terminal.isClaudeMode;
  const previousProfileId = terminal.claudeProfileId;

  const startTime = Date.now();

  try {
    debugLog('[ClaudeIntegration:invokeClaudeAsync] ========== INVOKE CLAUDE START (async) ==========');
    debugLog('[ClaudeIntegration:invokeClaudeAsync] Terminal ID:', terminal.id);
    debugLog('[ClaudeIntegration:invokeClaudeAsync] Requested profile ID:', profileId);
    debugLog('[ClaudeIntegration:invokeClaudeAsync] CWD:', cwd);
    debugLog('[ClaudeIntegration:invokeClaudeAsync] Dangerously skip permissions:', dangerouslySkipPermissions);

    // Compute extra flags for YOLO mode
    const extraFlags = dangerouslySkipPermissions ? YOLO_MODE_FLAG : undefined;

    terminal.isClaudeMode = true;
    // Store YOLO mode setting so it persists across profile switches
    terminal.dangerouslySkipPermissions = dangerouslySkipPermissions;
    SessionHandler.releaseSessionId(terminal.id);
    terminal.claudeSessionId = undefined;

    const projectPath = cwd || terminal.projectPath || terminal.cwd;

    // Ensure profile manager is initialized (async, yields to event loop)
    const profileManager = await initializeClaudeProfileManager();
    const activeProfile = profileId
      ? profileManager.getProfile(profileId)
      : profileManager.getActiveProfile();

    terminal.claudeProfileId = activeProfile?.id;

    debugLog('[ClaudeIntegration:invokeClaudeAsync] Profile resolution:', {
      previousProfileId,
      newProfileId: activeProfile?.id,
      profileName: activeProfile?.name,
      hasOAuthToken: !!activeProfile?.oauthToken,
      isDefault: activeProfile?.isDefault
    });

    // Async CLI invocation - non-blocking
    const cwdCommand = buildCdCommand(cwd, terminal.shellType);

    // Add timeout protection for CLI detection (10s timeout)
    const cliInvocationPromise = getClaudeCliInvocationAsync();
    let timeoutId: NodeJS.Timeout | undefined;
    const timeoutPromise = new Promise<never>((_, reject) => {
      timeoutId = setTimeout(() => reject(new Error('CLI invocation timeout after 10s')), 10000);
    });
    const { command: claudeCmd, env: claudeEnv } = await Promise.race([cliInvocationPromise, timeoutPromise])
      .finally(() => {
        if (timeoutId) clearTimeout(timeoutId);
      });

    const escapedClaudeCmd = escapeShellCommand(claudeCmd);
    const pathPrefix = buildPathPrefix(claudeEnv.PATH || '');
    const needsEnvOverride: boolean = !!(profileId && profileId !== previousProfileId);

    debugLog('[ClaudeIntegration:invokeClaudeAsync] Environment override check:', {
      profileIdProvided: !!profileId,
      previousProfileId,
      needsEnvOverride
    });

    // Try to execute using profile-specific method (configDir or temp-file) with async file operations
    const executed = await executeProfileCommandAsync({
      needsEnvOverride,
      activeProfile,
      cwdCommand,
      pathPrefix,
      escapedClaudeCmd,
      extraFlags,
      terminal,
      profileManager,
      projectPath,
      startTime,
      getWindow,
      onSessionCapture,
      logPrefix: '[ClaudeIntegration:invokeClaudeAsync]',
    });

    if (executed) {
      return; // Command already executed via configDir or temp-file method
    }

    // Fall back to default method
    if (activeProfile && !activeProfile.isDefault) {
      debugLog('[ClaudeIntegration:invokeClaudeAsync] Using terminal environment for non-default profile:', activeProfile.name);
    }

    const command = buildClaudeShellCommand(cwdCommand, pathPrefix, escapedClaudeCmd, { method: 'default' }, extraFlags);
    debugLog('[ClaudeIntegration:invokeClaudeAsync] Executing command (default method):', command);
    PtyManager.writeToPty(terminal, command);

    if (activeProfile) {
      profileManager.markProfileUsed(activeProfile.id);
    }

    finalizeClaudeInvoke(terminal, activeProfile, projectPath, startTime, getWindow, onSessionCapture);
    debugLog('[ClaudeIntegration:invokeClaudeAsync] ========== INVOKE CLAUDE COMPLETE (default) ==========');
  } catch (error) {
    // Reset terminal state on error to prevent inconsistent state
    terminal.isClaudeMode = wasClaudeMode;
    terminal.claudeSessionId = undefined;
    terminal.claudeProfileId = previousProfileId;
    const elapsed = Date.now() - startTime;
    debugError('[ClaudeIntegration:invokeClaudeAsync] Invocation failed:', error);
    debugError('[ClaudeIntegration:invokeClaudeAsync] Error details:', {
      terminalId: terminal.id,
      profileId,
      cwd,
      elapsedMs: elapsed,
      errorName: error instanceof Error ? error.name : 'Unknown',
      errorMessage: error instanceof Error ? error.message : String(error)
    });
    throw error; // Re-throw to allow caller to handle
  }
}

/**
 * Resume Claude asynchronously (non-blocking)
 *
 * Safe to call from Electron main process without blocking the event loop.
 * Uses async CLI detection which doesn't block on subprocess calls.
 */
export async function resumeClaudeAsync(
  terminal: TerminalProcess,
  sessionId: string | undefined,
  getWindow: WindowGetter
): Promise<void> {
  // Track terminal state for cleanup on error
  const wasClaudeMode = terminal.isClaudeMode;

  try {
    terminal.isClaudeMode = true;
    SessionHandler.releaseSessionId(terminal.id);

    // Async CLI invocation - non-blocking
    // Add timeout protection for CLI detection (10s timeout)
    const cliInvocationPromise = getClaudeCliInvocationAsync();
    let timeoutId: NodeJS.Timeout | undefined;
    const timeoutPromise = new Promise<never>((_, reject) => {
      timeoutId = setTimeout(() => reject(new Error('CLI invocation timeout after 10s')), 10000);
    });

    const { command: claudeCmd, env: claudeEnv } = await Promise.race([cliInvocationPromise, timeoutPromise])
      .finally(() => {
        if (timeoutId) clearTimeout(timeoutId);
      });

    const escapedClaudeCmd = escapeShellCommand(claudeCmd);
    const pathPrefix = buildPathPrefix(claudeEnv.PATH || '');

    // Always use --continue which resumes the most recent session in the current directory.
    // This is more reliable than --resume with session IDs since AI员工 already restores
    // terminals to their correct cwd/projectPath.
    //
    // Note: We clear claudeSessionId because --continue doesn't track specific sessions,
    // and we don't want stale IDs persisting through SessionHandler.persistSessionAsync().
    terminal.claudeSessionId = undefined;

    // Deprecation warning for callers still passing sessionId
    if (sessionId) {
      console.warn('[ClaudeIntegration:resumeClaudeAsync] sessionId parameter is deprecated and ignored; using claude --continue instead');
    }

    const command = `${pathPrefix}${escapedClaudeCmd} --continue`;

    // Use PtyManager.writeToPty for safer write with error handling
    PtyManager.writeToPty(terminal, `${command}\r`);

    // Only auto-rename if terminal has default name
    // This preserves user-customized names and prevents renaming on every resume
    if (shouldAutoRenameTerminal(terminal.title)) {
      terminal.title = 'Claude';
      const win = getWindow();
      if (win) {
        win.webContents.send(IPC_CHANNELS.TERMINAL_TITLE_CHANGE, terminal.id, 'Claude');
      }
    }

    // Persist session (async, fire-and-forget to prevent main process blocking)
    if (terminal.projectPath) {
      SessionHandler.persistSessionAsync(terminal);
    }
  } catch (error) {
    // Reset terminal state on error to prevent inconsistent state
    terminal.isClaudeMode = wasClaudeMode;
    // Note: Don't restore claudeSessionId since --continue doesn't use session IDs
    debugError('[ClaudeIntegration:resumeClaudeAsync] Resume failed:', error);
    throw error; // Re-throw to allow caller to handle
  }
}

/**
 * Configuration for waiting for Claude to exit
 */
interface WaitForExitConfig {
  /** Maximum time to wait for Claude to exit (ms) */
  timeout?: number;
  /** Interval between checks (ms) */
  pollInterval?: number;
}

/**
 * Result of waiting for Claude to exit
 */
interface WaitForExitResult {
  /** Whether Claude exited successfully */
  success: boolean;
  /** Error message if failed */
  error?: string;
  /** Whether the operation timed out */
  timedOut?: boolean;
}

/**
 * Shell prompt patterns that indicate Claude has exited and shell is ready
 * These patterns match common shell prompts across bash, zsh, fish, etc.
 */
const SHELL_PROMPT_PATTERNS = [
  /[$%#>❯]\s*$/m,                    // Common prompt endings: $, %, #, >, ❯
  /\w+@[\w.-]+[:\s]/,                // user@hostname: format
  /^\s*\S+\s*[$%#>❯]\s*$/m,          // hostname/path followed by prompt char
  /\(.*\)\s*[$%#>❯]\s*$/m,           // (venv) or (branch) followed by prompt
];

/**
 * Wait for Claude to exit by monitoring terminal output for shell prompt
 *
 * Instead of using fixed delays, this monitors the terminal's outputBuffer
 * for patterns indicating that Claude has exited and the shell prompt is visible.
 */
async function waitForClaudeExit(
  terminal: TerminalProcess,
  config: WaitForExitConfig = {}
): Promise<WaitForExitResult> {
  const { timeout = 5000, pollInterval = 100 } = config;

  debugLog('[ClaudeIntegration:waitForClaudeExit] Waiting for Claude to exit...');
  debugLog('[ClaudeIntegration:waitForClaudeExit] Config:', { timeout, pollInterval });

  // Capture current buffer length to detect new output
  const initialBufferLength = terminal.outputBuffer.length;
  const startTime = Date.now();

  return new Promise((resolve) => {
    const checkForPrompt = () => {
      const elapsed = Date.now() - startTime;

      // Check for timeout
      if (elapsed >= timeout) {
        console.warn('[ClaudeIntegration:waitForClaudeExit] Timeout waiting for Claude to exit after', timeout, 'ms');
        debugLog('[ClaudeIntegration:waitForClaudeExit] Timeout reached, Claude may not have exited cleanly');
        resolve({
          success: false,
          error: `Timeout waiting for Claude to exit after ${timeout}ms`,
          timedOut: true
        });
        return;
      }

      // Get new output since we started waiting
      const newOutput = terminal.outputBuffer.slice(initialBufferLength);

      // Check if we can see a shell prompt in the new output
      for (const pattern of SHELL_PROMPT_PATTERNS) {
        if (pattern.test(newOutput)) {
          debugLog('[ClaudeIntegration:waitForClaudeExit] Shell prompt detected after', elapsed, 'ms');
          debugLog('[ClaudeIntegration:waitForClaudeExit] Matched pattern:', pattern.toString());
          resolve({ success: true });
          return;
        }
      }

      // Also check if isClaudeMode was cleared (set by other handlers)
      if (!terminal.isClaudeMode) {
        debugLog('[ClaudeIntegration:waitForClaudeExit] isClaudeMode flag cleared after', elapsed, 'ms');
        resolve({ success: true });
        return;
      }

      // Continue polling
      setTimeout(checkForPrompt, pollInterval);
    };

    // Start checking
    checkForPrompt();
  });
}

/**
 * Switch terminal to a different Claude profile
 */
export async function switchClaudeProfile(
  terminal: TerminalProcess,
  profileId: string,
  getWindow: WindowGetter,
  invokeClaudeCallback: (terminalId: string, cwd: string | undefined, profileId: string, dangerouslySkipPermissions?: boolean) => Promise<void>,
  clearRateLimitCallback: (terminalId: string) => void
): Promise<{ success: boolean; error?: string }> {
  // Always-on tracing
  console.warn('[ClaudeIntegration:switchClaudeProfile] Called for terminal:', terminal.id, '| profileId:', profileId);
  console.warn('[ClaudeIntegration:switchClaudeProfile] Terminal state: isClaudeMode=', terminal.isClaudeMode);

  debugLog('[ClaudeIntegration:switchClaudeProfile] ========== SWITCH PROFILE START ==========');
  debugLog('[ClaudeIntegration:switchClaudeProfile] Terminal ID:', terminal.id);
  debugLog('[ClaudeIntegration:switchClaudeProfile] Target profile ID:', profileId);
  debugLog('[ClaudeIntegration:switchClaudeProfile] Terminal state:', {
    isClaudeMode: terminal.isClaudeMode,
    currentProfileId: terminal.claudeProfileId,
    claudeSessionId: terminal.claudeSessionId,
    projectPath: terminal.projectPath,
    cwd: terminal.cwd
  });

  // Ensure profile manager is initialized (async, yields to event loop)
  const profileManager = await initializeClaudeProfileManager();
  const profile = profileManager.getProfile(profileId);

  console.warn('[ClaudeIntegration:switchClaudeProfile] Profile found:', profile?.name || 'NOT FOUND');
  debugLog('[ClaudeIntegration:switchClaudeProfile] Target profile:', profile ? {
    id: profile.id,
    name: profile.name,
    hasOAuthToken: !!profile.oauthToken,
    isDefault: profile.isDefault
  } : 'NOT FOUND');

  if (!profile) {
    console.error('[ClaudeIntegration:switchClaudeProfile] Profile not found, aborting');
    debugError('[ClaudeIntegration:switchClaudeProfile] Profile not found, aborting');
    return { success: false, error: 'Profile not found' };
  }

  console.warn('[ClaudeIntegration:switchClaudeProfile] Switching to profile:', profile.name);
  debugLog('[ClaudeIntegration:switchClaudeProfile] Switching to Claude profile:', profile.name);

  if (terminal.isClaudeMode) {
    console.warn('[ClaudeIntegration:switchClaudeProfile] Sending exit commands (Ctrl+C, /exit)');
    debugLog('[ClaudeIntegration:switchClaudeProfile] Terminal is in Claude mode, sending exit commands');

    // Send Ctrl+C to interrupt any ongoing operation
    debugLog('[ClaudeIntegration:switchClaudeProfile] Sending Ctrl+C (\\x03)');
    // Use PtyManager.writeToPty for safer write with error handling
    PtyManager.writeToPty(terminal, '\x03');

    // Wait briefly for Ctrl+C to take effect before sending /exit
    await new Promise(resolve => setTimeout(resolve, 100));

    // Send /exit command
    debugLog('[ClaudeIntegration:switchClaudeProfile] Sending /exit command');
    // Use PtyManager.writeToPty for safer write with error handling
    PtyManager.writeToPty(terminal, '/exit\r');

    // Wait for Claude to actually exit by monitoring for shell prompt
    const exitResult = await waitForClaudeExit(terminal, { timeout: 5000, pollInterval: 100 });

    if (exitResult.timedOut) {
      console.warn('[ClaudeIntegration:switchClaudeProfile] Timed out waiting for Claude to exit, proceeding with caution');
      debugLog('[ClaudeIntegration:switchClaudeProfile] Exit timeout - terminal may be in inconsistent state');

      // Even on timeout, we'll try to proceed but log the warning
      // The alternative would be to abort, but that could leave users stuck
      // If this becomes a problem, we could add retry logic or abort option
    } else if (!exitResult.success) {
      console.error('[ClaudeIntegration:switchClaudeProfile] Failed to exit Claude:', exitResult.error);
      debugError('[ClaudeIntegration:switchClaudeProfile] Exit failed:', exitResult.error);
      // Continue anyway - the /exit command was sent
    } else {
      console.warn('[ClaudeIntegration:switchClaudeProfile] Claude exited successfully');
      debugLog('[ClaudeIntegration:switchClaudeProfile] Claude exited, ready to switch profile');
    }
  } else {
    console.warn('[ClaudeIntegration:switchClaudeProfile] NOT in Claude mode, skipping exit commands');
    debugLog('[ClaudeIntegration:switchClaudeProfile] Terminal NOT in Claude mode, skipping exit commands');
  }

  debugLog('[ClaudeIntegration:switchClaudeProfile] Clearing rate limit state for terminal');
  clearRateLimitCallback(terminal.id);

  const projectPath = terminal.projectPath || terminal.cwd;
  console.warn('[ClaudeIntegration:switchClaudeProfile] Invoking Claude with profile:', profileId, '| cwd:', projectPath, '| YOLO:', terminal.dangerouslySkipPermissions);
  debugLog('[ClaudeIntegration:switchClaudeProfile] Invoking Claude with new profile:', {
    terminalId: terminal.id,
    projectPath,
    profileId,
    dangerouslySkipPermissions: terminal.dangerouslySkipPermissions
  });
  // Pass the stored dangerouslySkipPermissions value to preserve YOLO mode across profile switches
  await invokeClaudeCallback(terminal.id, projectPath, profileId, terminal.dangerouslySkipPermissions);

  debugLog('[ClaudeIntegration:switchClaudeProfile] Setting active profile in profile manager');
  profileManager.setActiveProfile(profileId);

  console.warn('[ClaudeIntegration:switchClaudeProfile] COMPLETE');
  debugLog('[ClaudeIntegration:switchClaudeProfile] ========== SWITCH PROFILE COMPLETE ==========');
  return { success: true };
}
